
process {
    executor        = "slurm"
    scratch         = false
    maxRetries      = 3
    errorStrategy   = { task.exitStatus in [1,137,134,255,250] ? 'retry' : 'terminate' }
    //{ 1 * task.attempt }
    withLabel: simple {
        cpus        = 1
        queue       = 'compute'
        executor    = 'slurm'
        time        = '4h'
    }

    withLabel: heavy {
        cpus        = { 4 * task.attempt }
        queue       = 'compute'
        executor    = 'slurm'
        time        = '8h'
    }
}

executor {
    name = 'slurm'
    queueSize = 50
}

process {
    // Default resources
    cpus = 2
    memory = 4.GB
    time = 4.h
    
    errorStrategy = 'retry'
    maxRetries = 2
    
    // Process-specific settings
    withName: 'RAICHU_NORMALIZE' {
        cpus = 8
        time = 120.h
    }
    
    withName: 'PYHICCUPS_CALL_LOOPS' {
        cpus = 4
        memory = 8.GB
        time = 8.h
    }
    
    withName: 'COMBINE_LOOPS' {
        cpus = 1
        memory = 2.GB
        time = 1.h
    }
    
    withName: 'BEDPE_TO_ARC' {
        cpus = 1
        memory = 2.GB
        time = 1.h
    }
    
    withName: 'GENERATE_STATS' {
        cpus = 1
        memory = 2.GB
        time = 1.h
    }
}