conda.enabled = true

process {
    executor = 'slurm'
    queue = 'compute'
    queueSize = 100

    // Default resources
    cpus = 1
    time = 24.h
    
    // errorStrategy = 'retry'
    // maxRetries = 2
    
    // Process-specific settings
    withName: 'RAICHU_NORMALISE' {
        cpus = 48
        time = 120.h
    }
    
    withName: 'PYHICCUPS_CALL_LOOPS_PER_CHROM' {
        cpus = 8
        time = 120.h
    }
       

}