process {
    // Default resources
    cpus = 2
    memory = 4.GB
    time = 4.h
    
    errorStrategy = 'retry'
    maxRetries = 2
    
    // Process-specific settings
    withName: 'RAICHU_NORMALIZE' {
        cpus = 4
        memory = 8.GB
        time = 6.h
    }
    
    withName: 'PYHICCUPS_CALL_LOOPS' {
        cpus = 4
        memory = 8.GB
        time = 8.h
    }
    
    withName: 'COMBINE_LOOPS' {
        cpus = 1
        memory = 2.GB
        time = 1.h
    }
    
    withName: 'BEDPE_TO_ARC' {
        cpus = 1
        memory = 2.GB
        time = 1.h
    }
    
    withName: 'GENERATE_STATS' {
        cpus = 1
        memory = 2.GB
        time = 1.h
    }
}